# ============================================
# ✅ 변경 후 - kustomize/base/clustersecretstore.yaml
# ============================================
# 파일명 변경: secretstore.yaml → clustersecretstore.yaml
#
# 변경 사항:
# 1. SecretStore → ClusterSecretStore (클러스터 전역으로 변경)
# 2. serviceAccountRef를 ESO 자체 SA로 변경 (IRSA 보유)
# 3. namespace 명시 (ClusterSecretStore는 SA의 namespace를 알아야 함)
#
# ClusterSecretStore vs SecretStore:
# - SecretStore: 특정 Namespace에 바인딩, 해당 NS의 SA만 참조 가능
# - ClusterSecretStore: 클러스터 전역, 모든 NS의 ExternalSecret에서 참조 가능
# - 우리는 ESO SA가 external-secrets NS에 있고, 앱은 app-dev/app-prod NS에 있으므로
#   ClusterSecretStore가 필요
#
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore # ✅ 클러스터 전역
metadata:
  name: aws-secrets
  labels:
    app.kubernetes.io/name: app
    app.kubernetes.io/managed-by: kustomize
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets # ✅ ESO 자체 SA (IRSA 보유!)
            namespace: external-secrets # ✅ SA가 있는 namespace 명시
