# "External Secrets Operator와 AWS Secrets Manager를 연결하는 다리"
# - AWS Secrets Manager, GCP Secret Manager, HashiCorp Vault 등 지원

# service: 사용할 AWS 서비스
# - SecretsManager: 시크릿 관리 (우리가 사용)
# - ParameterStore: SSM Parameter Store
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets
  labels:
    app.kubernetes.io/name: app
spec:
  provider:
    aws:
      service: SecretsManager
      # [Refactor] 리전 하드코딩 제거 고려 -> 여기서는 Base 이므로 us-east-1 유지하되 주석 명시
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: app-sa
